# Generated by Django 6.1 on 2026-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsictu', '0005_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_name_per_creator',
        ),
        migrations.AddField(
            model_name='week',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='week',
            name='quiz_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
